name: pokertimer
version: 0.0.1
description: A sample web application
dependencies:
  firebase:
    git:
      url: git://github.com/pho3nixf1re/firebase-dart.git
      ref: dependency-update
  angular: '>=0.12.0'
  browser: any
  js: any
  paper_elements: any
  logging: any
  unittest: any
dev_dependencies:
  dart_to_js_script_rewriter: any

#This is dangerous but wanting to try the paper elements
dependency_overrides:
  analyzer: '>=0.15.6 <0.16.0'
  html5lib: '>=0.11.0 <0.12.0'
transformers:
- angular
- dart_to_js_script_rewriter   # needs to be after angular, perhaps last
