name: pokertimer
version: 0.0.1
description: Web app poker timer.
dependencies:
  firebase:
    git:
      url: git://github.com/pho3nixf1re/firebase-dart.git
      ref: dependency-update
  angular: '>=0.14.0'
  browser: any
  js: any
  paper_elements: any
  logging: any
dev_dependencies:
  dart_to_js_script_rewriter: any
  unittest: any

#This is dangerous but wanting to try the paper elements
dependency_overrides:
  analyzer: '>=0.15.6'
  html5lib: '>=0.11.0'
  web_components: '>=0.4.0'   #angular wanted older version... hopefully okay
  intl: '>=0.11.0'      #guess trying to get things working
  perf_api: '>=0.0.9'   #guess trying to get things working
transformers:
- angular
- dart_to_js_script_rewriter   # needs to be after angular, perhaps last
